version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: meubanco
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
