name: Pipeline de Integração Contínua

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest; fi

      - name: Rodar testes
        run: pytest -q

      - name: Simular deploy
        run: |
          mkdir dist
          cp app.py dist/
          echo "Deploy concluído! Código copiado para dist/"